# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install OpenLDAP
# --------------------------------------------------------------------------------------------------------------------------------------

- name: ðŸ›°ï¸  START - INSTALL OPENLDAP
  debug: msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

- name: ðŸš€ LDAP - Set LDAP ADMIN Password from instance configuration
  set_fact: current_ldap_admin_password={{ldap_admin_password  | default('P4ssw0rd!')}}

- name: ðŸŸ£  LDAP -  Demo UI Password {{current_ldap_admin_password}}
  debug:
    var: current_ldap_admin_password

- name: ðŸš€ LDAP - Set LDAP USERS Password from instance configuration
  set_fact: current_ldap_user_password={{ldap_user_password  | default('P4ssw0rd!')}}

- name: ðŸŸ£  LDAP -  Demo UI Password {{current_ldap_user_password}}
  debug:
    var: current_ldap_user_password

# - name: ADDONS -             âŽ Remove old OpenLDAP
#   community.kubernetes.k8s:
#     state: absent
#     template: ./templates/ldap/install-ldap.j2
#   #when: INSTALL_LDAP == true

- name: LDAP -               ðŸš€ Create OpenLDAP namespace
  community.kubernetes.k8s:
    name: "{{ ldap_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: LDAP -               ðŸš€ Create OpenLDAP namespace RoleBinding
  community.kubernetes.k8s:
    template: ./templates/ldap/anyuid-rolebinding.j2
    state: present

- name: LDAP -               ðŸš€ Install OpenLDAP
  community.kubernetes.k8s:
    state: present
    template: ./templates/ldap/install-ldap-persistent.j2
  #when: INSTALL_LDAP == true

# --------------------------------------------------------------------------------------------------------------------------------------
# Wait for LDAP ready
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ðŸ•¦ CHECK -  Wait for 2 pods Running in namespace {{ ldap_namespace }} (this might take some time)
  shell: |
    NUM_PODS=$(oc get po -n {{ ldap_namespace }} | grep openldap| grep Running| wc -l)
    echo $NUM_PODS
  register: kubectl_num_pods
  until: kubectl_num_pods.stdout|int >= 2
  retries: 100
  delay: 15

- name: ðŸ•¦ TIMESTAMP - END INSTALLATION - INSTALL OPENLDAP
  debug: msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"
