# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Create OCP Demouser Account
# --------------------------------------------------------------------------------------------------------------------------------------

- name: üõ∞Ô∏è  START - CREATE USER
  debug: msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

- name: üë©‚Äçüíª DEMO USER - Check OCP Demouser Account
  shell: |
    oc get serviceaccount --ignore-not-found -n default demo-admin
  ignore_errors: true
  register: USER_EXISTS

- name: üë©‚Äçüíª DEMO USER - Create OCP Demouser Account
  shell: |
    oc project {{project}} 
    oc create serviceaccount -n default demo-admin
    oc create clusterrolebinding test-admin --clusterrole=cluster-admin --serviceaccount=default:demo-admin
    oc create clusterrolebinding ibm-zen-operator-serviceaccount --clusterrole=cluster-admin --serviceaccount=ibm-common-services:ibm-zen-operator-serviceaccount
  ignore_errors: true
  register: demo_account
  when: USER_EXISTS.stdout|length == 0
